### ISSUE TITLE
Add KCPTUN_MODE to environment

### ISSUE THREAD

**Issue by huntingtonanalytics** [yaleh/kcp-shadowsocks-server#1]
This is an amazing little piece of software. However I'd love to use KCPTUN_MODE=fast3! Can you make it a var??

**Comment by yaleh** [comment]
Sorry, I didn't notice this issue until today. I'll look at it.

**Comment by yaleh** [comment]
@n0cebo I checked the code, and found that KCPTUN_MODE is supported by the manual mode:

```
docker run -d --restart=always -e 'SS_PASSWORD=SHADOWSOCKS_PASSWORD' -e 'KCPTUN_PASSWORD=balancing' -e  KCPTUN_MODE='fast3' -p 8338:8338/tcp -p 41111:41111/udp --name=my-kcp-ss yaleh/kcp-shadowsocks-server
```

but not the bootstrap mode.

So, what you want is to support KCPTUN_MODE with the bootstrap?
