### ISSUE TITLE
非常棒的项目，但请考虑增加hostname到environment

### ISSUE THREAD

**Issue by tony1016** [yaleh/kcp-shadowsocks-server#2]
项目非常棒，鼓励一下。但是目前扫码或者链接的主机地址都不对，请考虑在environment中增加hostname

**Comment by yaleh** [comment]
Sorry, I haven't check issues of this project for months.

I checked the code and found that the hostname in the link can be configured when running bootstrap with an env HOST:

```
docker run -t -i --rm --network=host \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e HOST=YOUR_HOSTNAME \
  yaleh/kcp-shadowsocks-server bootstrap
```

And I'm going to update the URI to SIP002. I'll double check it and make sure this env works. Thank you!
